name: Build CPython 3.10 for Windows

on:
  # This allows you to manually trigger the workflow from the GitHub Actions tab
  workflow_dispatch:
  # You can also trigger it on a push to a specific branch in your fork
  # push:
  #   branches: [ main ] 

jobs:
  build: # Job name
    # runs-on MUST be a direct child of the job name (build)
    runs-on: windows-latest 
    
    # strategy is optional but must be a direct child of the job name (build)
    strategy:
      matrix:
        # We only want Windows, so we define it here.
        # This makes the runs-on line above effectively equal to windows-latest.
        os: [windows-latest]
    
    steps:
    
    # 1. CHECKOUT - This step is essential and must be its own step.
    #    It pulls the CPython source code onto the runner.
    - name: Checkout CPython Source (3.10 branch)
      uses: actions/checkout@v4
      with:
        # Check out the CPython repository directly.
        repository: Randy420Marsh/cpython
        ref: 3.10 # Target the 3.10 branch

    # 2. SETUP PYTHON - This step is for setting up a *host* Python, 
    #    which is useful for running tools like setup.py, but not strictly
    #    necessary for the core PCbuild.bat script. It removes the warnings, though.
    - name: Set up Host Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Using a newer version is fine for the host

    # 3. BUILD
    - name: Build Python 3.10 (64-bit Release)
      # The CPython build system on Windows uses a PCbuild directory and batch files.
      run: PCbuild\build.bat -e -r -x64
      # Note: This step can take 15-30 minutes or more depending on the runner.
      
    # 4. ZIP
    - name: Zip the Built Directory
      run: Compress-Archive -Path PCbuild\amd64\* -DestinationPath cpython-3.10-windows-x64.zip
      shell: powershell
      
    # 5. UPLOAD ARTIFACT
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cpython-3.10-windows-x64-build
        path: cpython-3.10-windows-x64.zip
        retention-days: 7
